version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /DiscoveryMessageTests
      - /LegoInfrared
      - /LegoTrain
      - /SignalSwitch
      - /TrainDetect
    schedule:
      interval: weekly
    labels:
      - dependency update
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependency update
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /LegoTrain
    schedule:
      interval: weekly
    labels:
      - dependency update
    groups:
      docker-images:
        patterns:
          - "*"