//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalSwitch
{
    
    internal partial class ResourceWeb
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((ResourceWeb.manager == null))
                {
                    ResourceWeb.manager = new System.Resources.ResourceManager("SignalSwitch.ResourceWeb", typeof(ResourceWeb).Assembly);
                }
                return ResourceWeb.manager;
            }
        }
        internal static string GetString(ResourceWeb.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            style = -5605,
        }
    }
}
